FROM python:3.9

WORKDIR /pvoutput

RUN pip install -e git+https://github.com/openclimatefix/pvoutput#egg=pvoutput > /dev/null

COPY examples/ /pvoutput/examples/

EXPOSE 1234

CMD ["jupyter", "notebook", "--allow-root", "--ip", "0.0.0.0", "--port", "1234", "--no-browser", "/pvoutput/examples/quick_start.ipynb"]
